mv  bcpmx_alldb.sh  Scaffale_scripts/da_sistemare
mv  bcpmx_in_db-new.sh  Scaffale_scripts/da_sistemare
mv  bcpmx_in_db.sh  Scaffale_scripts/da_sistemare
mv  bcpmx_singolodb.sh  Scaffale_scripts/da_sistemare
mv  checkpoint_a_db_for_a_time.sh  Scaffale_scripts/da_sistemare
mv  connections-report-tempi.sh  Scaffale_scripts/da_sistemare
mv  create_db_da_ddl.sh  Scaffale_scripts/da_sistemare
mv  creazione_dei_nuovi_piccoli_db_su_dev.sh  Scaffale_scripts/da_sistemare
mv  creazione_del_nuovo_CAP_PROD.sh  Scaffale_scripts/da_sistemare
mv  cronner.sh  Scaffale_scripts/da_sistemare
mv  crontester.sh  Scaffale_scripts/da_sistemare
mv  dammi_data_e_ora.sh  Scaffale_scripts/da_sistemare
mv  db-ampliamento-dati.sh  Scaffale_scripts/da_sistemare
mv  db-ampliamento-device.sh  Scaffale_scripts/da_sistemare
mv  db-ampliamento-misto.sh  Scaffale_scripts/da_sistemare
mv  db-prerequisiti-recreate-db.sh  Scaffale_scripts/da_sistemare
mv  db-pulizia-tempdb.sh  Scaffale_scripts/da_sistemare
mv  db-singolo-space-full-report.sh  Scaffale_scripts/da_sistemare
mv  db-singolo-space-report-con-dataora.sh  Scaffale_scripts/da_sistemare
mv  db-singolo-space-report-media-eval.sh  Scaffale_scripts/da_sistemare
mv  db-space-report.sh  Scaffale_scripts/da_sistemare
mv  db-tempdb-alert.sh  Scaffale_scripts/da_sistemare
mv  db-tempdb-study.sh  Scaffale_scripts/da_sistemare
mv  dbccmx_checkalloc.sh  Scaffale_scripts/da_sistemare
mv  ddlmx_alldb.sh  Scaffale_scripts/da_sistemare
mv  ddlmx_alldb_singletype.sh  Scaffale_scripts/da_sistemare
mv  drop_tabelle_murex.sh  Scaffale_scripts/da_sistemare
mv  dumpmx_1shot_alldb.sh  Scaffale_scripts/da_sistemare
mv  dumpmx_1shot_singolodb_striped.sh  Scaffale_scripts/da_sistemare
mv  dumpmx_singolodb.sh  Scaffale_scripts/da_sistemare
mv  dumpmx_singolodb_striped.sh  Scaffale_scripts/da_sistemare
mv  esecutore_estemporaneo.sh  Scaffale_scripts/da_sistemare
mv  esegui_sql.sh  Scaffale_scripts/da_sistemare
mv  fixsegmap_alldb.sh  Scaffale_scripts/da_sistemare
mv  fixsegmap_singolodb.sh  Scaffale_scripts/da_sistemare
mv  fixsegmap_singolodb_tutti_misti.sh  Scaffale_scripts/da_sistemare
mv  grant-all-to-dbo-singolo-db.sh  Scaffale_scripts/da_sistemare
mv  grant-select-to-ReadOnly.sh  Scaffale_scripts/da_sistemare
mv  grant-select-to-user-in-crontab.sh  Scaffale_scripts/da_sistemare
mv  grant-select-to-user.sh  Scaffale_scripts/da_sistemare
mv  kill_all_dbcc_sessions.sh  Scaffale_scripts/da_sistemare
mv  kill_per_troppe_connessioni.sh  Scaffale_scripts/da_sistemare
mv  loadmx_in_crontab_striped.sh  Scaffale_scripts/da_sistemare
mv  loadmx_preservando_sysusers.sh  Scaffale_scripts/da_sistemare
mv  loadmx_preservando_sysusers_striped.sh  Scaffale_scripts/da_sistemare
mv  misurazione_occupazione_max_log.sh  Scaffale_scripts/da_sistemare
mv  mon-mail-tempdb-conn.sh  Scaffale_scripts/da_sistemare
mv  mon-shared-mem-sybase.new.sh  Scaffale_scripts/da_sistemare
mv  mon-shared-mem-sybase.old.sh  Scaffale_scripts/da_sistemare
mv  mon-shared-mem-sybase.pgsp.sh  Scaffale_scripts/da_sistemare
mv  mon-shared-mem-sybase.sh  Scaffale_scripts/da_sistemare
mv  prova_prova.sh  Scaffale_scripts/da_sistemare
mv  report-operazioni-fallite.sh  Scaffale_scripts/da_sistemare
mv  report-processi-locks.sh  Scaffale_scripts/da_sistemare
mv  report-sender.sh  Scaffale_scripts/da_sistemare
mv  riduzione-plf.sh  Scaffale_scripts/da_sistemare
mv  ristrutt_di_un_db.sh  Scaffale_scripts/da_sistemare
mv  runisql_con_output.sh  Scaffale_scripts/da_sistemare
mv  stop_ase_4tempi-nochk.sh  Scaffale_scripts/da_sistemare
mv  tempi-impiegati-backup-tivoli.sh  Scaffale_scripts/da_sistemare
mv  test-mail.sh  Scaffale_scripts/da_sistemare
